language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update
  - composer require --dev codeclimate/php-test-reporter:dev-master

install:
  - composer install --prefer-source --no-interaction --dev
  
before_script:
  - mkdir -p build/logs

script: 
  - phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml
  
after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/test-reporter; fi;'

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
